### ISSUE TITLE
Add the possibility to measure using two ELMs

### ISSUE THREAD

**Issue by prakhub** [hephy-dd/diode-measurement#89]
For some I-V measurements, it would be advantageous to measure with two electrometers at the same time (pad and guard ring current).

Most important would be to log the current to a file, a live view of the ELM2 current would be an added bonus.

**Comment by arnobaer** [comment]
Actually this is quite trivial to achieve by copy/pasting the ELM role as ELM2 resulting in an added configuration tab and plot series if selected.
